from app.tools.registry import get_agent
from app.orchestration.project_builder import project_builder


class TaskExecutor:

    def execute(self, task):
        """
        Execute a task generated by the planner.
        """

        # =====================================================
        # SOFTWARE ENGINEER
        # =====================================================

        if task.agent == "software_engineer_agent":

            return project_builder.build(
                task.description
            )

        # =====================================================
        # GENERAL CHAT
        # =====================================================

        if task.agent == "general_chat":

            return {
                "success": True,
                "response": "General chat should be handled by the brain."
            }

        # =====================================================
        # OTHER AGENTS
        # =====================================================

        agent = get_agent(task.agent)

        if agent is None:

            return {
                "success": False,
                "response": f"Agent '{task.agent}' not found."
            }

        try:

            result = agent.run(
                task.description
            )

            task.status = "completed"
            task.result = result

            return result

        except Exception as e:

            task.status = "failed"

            return {
                "success": False,
                "response": str(e)
            }


executor = TaskExecutor()