FASTAPI_TEMPLATE = {
    "app/main.py": """
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def home():
    return {"message":"Hello from ULTRON"}
""",

    "requirements.txt": """
fastapi
uvicorn
""",

    "README.md": """
# Generated by ULTRON
"""
}