version: '3'
services:
  app:
    build: .
    environment:
      - DATABASE_URL=sqlite:///database/todo.db
      - SECRET_KEY=secret_key
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

  redis:
    image: redis:latest
    restart: always

  celery:
    build: .
    command: celery -A app.main worker --loglevel=info
    environment:
      - DATABASE_URL=sqlite:///database/todo.db
      - SECRET_KEY=secret_key
    depends_on:
      - app
      - redis
    restart: always

  celery-beat:
    build: .
    command: celery -A app.main beat --loglevel=info
    environment:
      - DATABASE_URL=sqlite:///database/todo.db
      - SECRET_KEY=secret_key
    depends_on:
      - app
      - redis
    restart: always

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - celery
      - redis
    restart: always