version: '3'
services:
  blog-api:
    build: .
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database
      - SECRET_KEY=secret_key
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: